version: 2.1

orbs:
    azure-acr: circleci/azure-acr@0.2.1

jobs:
   build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - azure-acr/build-and-push-image:
          dockerfile: Dockerfile
          login-server-name: success.azurecr.io
          registry-name: success
          repo: simple-java-app

workflows:
  build-deploy-java-app:
    jobs:
      - build-and-test